// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkBJlc_ubL1Iw-yX6m12DCPH6V1hoEs-A',
    appId: '1:751038134165:android:e2d588fb46941ed9f2289c',
    messagingSenderId: '751038134165',
    projectId: 'note-box-e0b75',
    storageBucket: 'note-box-e0b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0N9vx-KHi2dDsbQvDF9ENytAYui2wAcM',
    appId: '1:751038134165:ios:15916ca37e4408cff2289c',
    messagingSenderId: '751038134165',
    projectId: 'note-box-e0b75',
    storageBucket: 'note-box-e0b75.firebasestorage.app',
    androidClientId: '751038134165-0m5e5ov1ha61s2hhfkam71bp29c7v1l4.apps.googleusercontent.com',
    iosClientId: '751038134165-jark75jqe7607hthlgabjpvln83dt4gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteBox',
  );

}